# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 16:09
from __future__ import unicode_literals

import campusradio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=campusradio.models.get_host_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=campusradio.models.get_show_image_path)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='shows',
            field=models.ManyToManyField(to='campusradio.Show'),
        ),
    ]
