# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusradio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='profile_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='profile_image',
            new_name='image',
        ),
    ]
