# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 18:53
from __future__ import unicode_literals

import campusradio.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campusradio', '0002_auto_20170217_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=campusradio.models.get_host_image_path)),
                ('archive_link', models.URLField()),
                ('mp3_link', models.URLField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campusradio.Show')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=campusradio.models.get_image_path)),
                ('description', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('markdown_content', models.TextField()),
                ('html_content', models.TextField()),
            ],
        ),
    ]
