# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusradio', '0003_episode_image_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='mp3_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
