# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusradio', '0005_auto_20170217_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
