# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusradio', '0006_auto_20170217_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='waveform_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
