# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 22:37
from __future__ import unicode_literals

import campusradio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusradio', '0008_show_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markdown_content', models.TextField()),
                ('html_content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=campusradio.models.get_image_path)),
            ],
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ('-added',)},
        ),
    ]
