# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 22:43
from __future__ import unicode_literals

import campusradio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusradio', '0010_auto_20170218_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=campusradio.models.get_index_path),
        ),
    ]
