# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusradio', '0013_auto_20170219_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('sort',)},
        ),
        migrations.AddField(
            model_name='page',
            name='sort',
            field=models.SmallIntegerField(default=0),
        ),
    ]
